[package]
name = "libpq-serde-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["extra-traits"] }   # turning tokens to an ast
quote = "1.0" # producing tokens to return to the compiler
deluxe = "0.5.0"
proc-macro2 = "1.0.95"
